---
title: "reorganization"
author: "ken"
date: "4/7/2021"
output: html_document
---

# Ideas for reorganization of notes etc.

## lecture notes

- move the choosing and selection piece to before inference  done
- add rowwise intro to that (with list-columns?) DONE needs editing
- change all the `map` stuff to  `rowwise`, including simulations (power and bootstrap, etc) done
- change `rstan` to `cmdstanr` done in notes, now PASIAS
- have one project for all the lecture notes

## PASIAS

- move the chapter on choosing and selection to before inference done
- subdivide the chapters to correspond better to the pieces of lecture notes including for D29
- edit out all the `map` stuff and replace by `rowwise` (in the same manner as lecture notes)
- `summarize_at` etc (do with `across`) DONE
- cmdstanr replaces rstan done
- `_if` and `_at` done
- do the actual maps with leaflet

## D29 

- also get rid of `map` DONE
- make sure all the `gather`/`spread` is gone done
- introduce some new examples (maybe more realistic ones?)
- make the map stuff leaflet rather than ggmap done
- `_if` and `_at` done
- make mapping.Rmd into slides  done

## data files

- move these off banks and onto the website. done.
- change links in notes and pasias
- create a repo called datafiles for them. done

## plan of attack

- start with C32 lecture notes
- move choosing piece and think about tidying piece (I think it can stay)
- move choosing chapter in pasias
- add rowwise piece to notes, after the `join` stuff
  - list columns
  - nest_by - unnest
- maybe turn bootstrap piece into more general discussion of simulation (or not, leaving it for C33)
- take out `map` discussion from notes, wherever it appears

- see if any problems replacing all `map` by `rowwise`

- split chapters of PASIAS for C32-C33

- add problems from recent assignments to pasias

- get `gather`-`spread` out of D29 DONE
- new examples
- split PASIAS for this too

- make sure nothing old left in PASIAS (gather/spread/map)


- c33:
  - cmdstan
  
## re-recording because of map/rowwise

- c32 
  - inference2
  - functions
  - bootstrap
  - rstan (with cmdstan anyway, still need to rewrite)
  - inference3
  
- d29 
  - discrim (can probably avoid)
  - cluster
  - time series (not recorded anyway)
  - anova